### ISSUE TITLE
You need at least read:org scope or user scope to list your organizations

### ISSUE THREAD

**Issue by shenwei356** [zmmbreeze/octocard#24]
I do not have any organizations. Can you fix this?

**Comment by shenwei356** [comment]
It seems that GitHub API changed

**Comment by zmmbreeze** [comment]
Fixed https://github.com/zmmbreeze/octocard-server/issues/11.

Revoke your [octocard](https://github.com/settings/applications), then [unlogin](http://octocard.in/unlogin/) and [sign up](http://octocard.in/) agin.
