### ISSUE TITLE
TLS for octocard.in

### ISSUE THREAD

**Issue by dschuermann** [zmmbreeze/octocard#25]
I can no longer use octocard.in on my website, because octocard.in does not support TLS connections. If I include the non-TLS version in my TLS-secured website it is not displayed, because browsers will consider it as insecure content.

It would be awesome if you would support a TLS version, i.e., https://octocard.in
Maybe, cloudflare is a simple and free of charge solution?

**Comment by dschuermann** [comment]
Any updates on this issue?

**Comment by zmmbreeze** [comment]
Hi @dschuermann , it has been done. https://octocard.in/
Feel free to use it. 😄

**Comment by dschuermann** [comment]
Great!

Unfortunately, looks like there need to be changes to the script to make this work. In Firebug I get: "Blocked loading mixed active content “http://octocard.in/api?dataType=theme&name=&callback=githubcardjsonp1481119058846”"

See https://www.sufficientlysecure.org/

**Comment by zmmbreeze** [comment]
Done!

**Comment by dschuermann** [comment]
Awesome, it works! Thank you so much.
